In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("C:\\Users\\suraj\\Downloads\\tmdb_5000_movies.csv\\tmdb_5000_movies.csv")

In [3]:
df2 = pd.read_csv("C:\\Users\\suraj\\Downloads\\tmdb_5000_credits.csv\\tmdb_5000_credits.csv")

In [4]:
df1.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
df2.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
df2.rename(columns = {
    'movie_id':'id'
},inplace=True)

In [7]:
df = pd.merge(df1,df2,on='id')

In [8]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
data = df['genres'][0]

In [10]:
data

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
import json

In [12]:
parse_data = json.loads(data)

In [13]:
parse_data

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [14]:
result = [item['name'] for item in parse_data]

In [15]:
result2 = " ".join(result)

In [16]:
result2

'Action Adventure Fantasy Science Fiction'

In [17]:
def extract_genres(data):
    parse_data = json.loads(data)
    result = [item['name'] for item in parse_data]
    result2 = " ".join(result)
    return result2

In [18]:
df['genres']=df['genres'].apply(extract_genres)

In [19]:
df['genres']

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801
4802                                 Documentary
Name: genres, Length: 4803, dtype: object

In [20]:
df['keywords']=df['keywords'].apply(extract_genres)

In [21]:
df['keywords'][0]

'culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d'

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title_x               4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  title_y               4803 non-null   object
 21  cast                  4803 non-null   object
 22  crew                  4803 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 863.2+ KB

In [23]:
df['spoken_languages']=df['spoken_languages'].apply(extract_genres)

In [24]:
df['title_y']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4798                                 El Mariachi
4799                                   Newlyweds
4800                   Signed, Sealed, Delivered
4801                            Shanghai Calling
4802                           My Date with Drew
Name: title_y, Length: 4803, dtype: object

In [25]:
columns_to_drop= ['homepage','original_title','overview','popularity','production_companies','production_countries','release_date','revenue','runtime','status','tagline','title_x','vote_average','vote_count','title_y']

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title_x               4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  title_y               4803 non-null   object
 21  cast                  4803 non-null   object
 22  crew                  4803 non-null   object
dtypes: float64(3), int64(4), object(16)
memory usage: 863.2+ KB

In [27]:
df.drop(columns=columns_to_drop,inplace=True)

In [29]:
df

,budget,genres,id,keywords,original_language,spoken_languages,cast,crew
0,237000000,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,en,English EspaÃ±ol,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,en,English,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,Action Adventure Crime,206647,spy based on novel secret agent sequel mi6 bri...,en,FranÃ§ais English EspaÃ±ol Italiano Deutsch,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,Action Crime Drama Thriller,49026,dc comics crime fighter terrorist secret ident...,en,English,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,Action Adventure Science Fiction,49529,based on novel mars medallion space travel pri...,en,English,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4798,220000,Action Crime Thriller,9367,united statesâ€“mexico barrier legs arms paper k...,es,EspaÃ±ol,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,9000,Comedy Romance,72766,,en,,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,0,Comedy Drama Romance TV Movie,231617,date love at first sight narration investigati...,en,English,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,0,,126186,,en,English,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,0,Documentary,25975,obsession camcorder crush dream girl,en,English,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [30]:
import pandas as pd

In [31]:
df['cast']=df['cast'].str.lower()

In [32]:
df['cast'][0]

'[{"cast_id": 242, "character": "jake sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "sam worthington", "order": 0}, {"cast_id": 3, "character": "neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "zoe saldana", "order": 1}, {"cast_id": 25, "character": "dr. grace augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "sigourney weaver", "order": 2}, {"cast_id": 4, "character": "col. quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "stephen lang", "order": 3}, {"cast_id": 5, "character": "trudy chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "michelle rodriguez", "order": 4}, {"cast_id": 8, "character": "selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "giovanni ribisi", "order": 5}, {"cast_id": 7, "character": "norm spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "joel david moore", "order": 6}, {"cast_id": 9, "character": "moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "cch pounder", "order": 7}, {"cast_id": 11, "character": "eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "wes studi", "order": 8}, {"cast_id": 10, "character": "tsu\'tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "laz alonso", "order": 9}, {"cast_id": 12, "character": "dr. max patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "dileep rao", "order": 10}, {"cast_id": 13, "character": "lyle wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "matt gerald", "order": 11}, {"cast_id": 32, "character": "private fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "sean anthony moran", "order": 12}, {"cast_id": 33, "character": "cryo vault med tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "jason whyte", "order": 13}, {"cast_id": 34, "character": "venture star crew chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "scott lawrence", "order": 14}, {"cast_id": 35, "character": "lock up trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "kelly kilgour", "order": 15}, {"cast_id": 36, "character": "shuttle pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "james patrick pitt", "order": 16}, {"cast_id": 37, "character": "shuttle co-pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "sean patrick murphy", "order": 17}, {"cast_id": 38, "character": "shuttle crew chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "peter dillon", "order": 18}, {"cast_id": 39, "character": "tractor operator / troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "kevin dorman", "order": 19}, {"cast_id": 40, "character": "dragon gunship pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "kelson henderson", "order": 20}, {"cast_id": 41, "character": "dragon gunship gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "david van horn", "order": 21}, {"cast_id": 42, "character": "dragon gunship navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "jacob tomuri", "order": 22}, {"cast_id": 43, "character": "suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "michael blain-rozgay", "order": 23}, {"cast_id": 44, "character": "suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "jon curry", "order": 24}, {"cast_id": 46, "character": "ambient room tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "luke hawker", "order": 25}, {"cast_id": 47, "character": "ambient room tech / troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "woody schultz", "order": 26}, {"cast_id": 48, "character": "horse clan leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "peter mensah", "order": 27}, {"cast_id": 49, "character": "link room tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "sonia yee", "order": 28}, {"cast_id": 50, "character": "basketball avatar / troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "jahnel curfman", "order": 29}, {"cast_id": 51, "character": "basketball avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "ilram choi", "order": 30}, {"cast_id": 52, "character": "na\'vi child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "kyla warren", "order": 31}, {"cast_id": 53, "character": "troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "lisa roumain", "order": 32}, {"cast_id": 54, "character": "troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "debra wilson", "order": 33}, {"cast_id": 57, "character": "troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "chris mala", "order": 34}, {"cast_id": 55, "character": "troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "taylor kibby", "order": 35}, {"cast_id": 56, "character": "troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "jodie landau", "order": 36}, {"cast_id": 58, "character": "troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "julie lamm", "order": 37}, {"cast_id": 59, "character": "troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "cullen b. madden", "order": 38}, {"cast_id": 60, "character": "troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "joseph brady madden", "order": 39}, {"cast_id": 61, "character": "troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "frankie torres", "order": 40}, {"cast_id": 62, "character": "troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "austin wilson", "order": 41}, {"cast_id": 63, "character": "troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "sara wilson", "order": 42}, {"cast_id": 64, "character": "troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "tamica washington-miller", "order": 43}, {"cast_id": 65, "character": "op center staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "lucy briant", "order": 44}, {"cast_id": 66, "character": "op center staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "nathan meister", "order": 45}, {"cast_id": 67, "character": "op center staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "gerry blair", "order": 46}, {"cast_id": 68, "character": "op center staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "matthew chamberlain", "order": 47}, {"cast_id": 69, "character": "op center staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "paul yates", "order": 48}, {"cast_id": 70, "character": "op center duty officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "wray wilson", "order": 49}, {"cast_id": 71, "character": "op center staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "james gaylyn", "order": 50}, {"cast_id": 72, "character": "dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "melvin leno clark iii", "order": 51}, {"cast_id": 73, "character": "dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "carvon futrell", "order": 52}, {"cast_id": 74, "character": "dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "brandon jelkes", "order": 53}, {"cast_id": 75, "character": "dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "micah moch", "order": 54}, {"cast_id": 76, "character": "dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "hanniyah muhammad", "order": 55}, {"cast_id": 77, "character": "dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "christopher nolen", "order": 56}, {"cast_id": 78, "character": "dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "christa oliver", "order": 57}, {"cast_id": 79, "character": "dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "april marie thomas", "order": 58}, {"cast_id": 80, "character": "dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "bravita a. threatt", "order": 59}, {"cast_id": 81, "character": "mining chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "colin bleasdale", "order": 60}, {"cast_id": 82, "character": "veteran miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "mike bodnar", "order": 61}, {"cast_id": 83, "character": "richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "matt clayton", "order": 62}, {"cast_id": 84, "character": "nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "nicole dionne", "order": 63}, {"cast_id": 85, "character": "trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "jamie harrison", "order": 64}, {"cast_id": 86, "character": "trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "allan henry", "order": 65}, {"cast_id": 87, "character": "ground technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "anthony ingruber", "order": 66}, {"cast_id": 88, "character": "flight crew mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "ashley jeffery", "order": 67}, {"cast_id": 14, "character": "samson pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "dean knowsley", "order": 68}, {"cast_id": 89, "character": "trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "joseph mika-hunt", "order": 69}, {"cast_id": 90, "character": "banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "terry notary", "order": 70}, {"cast_id": 91, "character": "soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "kai pantano", "order": 71}, {"cast_id": 92, "character": "blast technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "logan pithyou", "order": 72}, {"cast_id": 93, "character": "vindum raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "stuart pollock", "order": 73}, {"cast_id": 94, "character": "hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "raja", "order": 74}, {"cast_id": 95, "character": "ops centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "gareth ruck", "order": 75}, {"cast_id": 96, "character": "engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "rhian sheehan", "order": 76}, {"cast_id": 97, "character": "col. quaritch\'s mech suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "t. j. storm", "order": 77}, {"cast_id": 98, "character": "female marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "jodie taylor", "order": 78}, {"cast_id": 99, "character": "ikran clan leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "alicia vela-bailey", "order": 79}, {"cast_id": 100, "character": "geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "richard whiteside", "order": 80}, {"cast_id": 101, "character": "na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "nikie zambo", "order": 81}, {"cast_id": 102, "character": "ambient room tech / troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "julene renee", "order": 82}]'

In [33]:
data=json.loads(df['cast'][0])

In [34]:
''.join(data[0]['name'].split())

'samworthington'

In [35]:
a=5
name =[]
for item in data:
    if(a):
        name.append(''.join(item['name'].split()))
        a=a-1
    else:
        break
print(' '.join(name))

samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez

In [36]:
data

[{'cast_id': 242,
  'character': 'jake sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'sam worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'zoe saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'dr. grace augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'sigourney weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'col. quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'stephen lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'trudy chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'michelle rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'giovanni ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'norm spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'joel david moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'cch pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'wes studi',
  'order': 8},
 {'cast_id': 10,
  'character': "tsu'tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'laz alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'dr. max patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'dileep rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'lyle wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'matt gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'private fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'sean anthony moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'cryo vault med tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'jason whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'venture star crew chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'scott lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'lock up trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'kelly kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'shuttle pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'james patrick pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'shuttle co-pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'sean patrick murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'shuttle crew chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'peter dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'tractor operator / troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'kevin dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'dragon gunship pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'kelson henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'dragon gunship gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'david van horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'dragon gunship navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'jacob tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'michael blain-rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'jon curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'ambient room tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'luke hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'ambient room tech / troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'woody schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'horse clan leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'peter mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'link room tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'sonia yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'basketball avatar / troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'jahnel curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'basketball avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'ilram choi',
  'order': 30},
 {'cast_id': 52,
  'character': "na'vi child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'kyla warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'lisa roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'debra wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'chris mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'taylor kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'jodie landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'julie lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'cullen b. madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'joseph brady madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'frankie torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'austin wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'sara wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'tamica washington-miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'op center staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'lucy briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'op center staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'nathan meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'op center staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'gerry blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'op center staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'matthew chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'op center staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'paul yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'op center duty officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'wray wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'op center staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'james gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'melvin leno clark iii',
  'order': 51},
 {'cast_id': 73,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'carvon futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'brandon jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'micah moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'hanniyah muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'christopher nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'christa oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'april marie thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'bravita a. threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'mining chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'colin bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'veteran miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'mike bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'matt clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'nicole dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'jamie harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'allan henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'ground technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'anthony ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'flight crew mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'ashley jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'samson pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'dean knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'joseph mika-hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'terry notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'kai pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'blast technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'logan pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'vindum raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'stuart pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'ops centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'gareth ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'rhian sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "col. quaritch's mech suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 't. j. storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'female marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'jodie taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'ikran clan leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'alicia vela-bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'richard whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'nikie zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'ambient room tech / troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'julene renee',
  'order': 82}]

In [37]:
data[0]['name']

'sam worthington'

In [38]:
def extract_names(data):
    a = 5
    name = []
    parse_data = json.loads(data)
    for item in parse_data:
        if a:
            name.append(''.join(item['name'].split()))
            a = a - 1
        else:
            break      
    return ' '.join(name)

In [39]:
df['name']= df['cast'].apply(extract_names)

In [40]:
df['name'][0]

'samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez'

In [41]:
df.drop(columns=['cast'],inplace=True)

In [42]:
data2 = json.loads(df['crew'][1])

In [43]:
data2

[{'credit_id': '52fe4232c3a36847f800b579',
  'department': 'Camera',
  'gender': 2,
  'id': 120,
  'job': 'Director of Photography',
  'name': 'Dariusz Wolski'},
 {'credit_id': '52fe4232c3a36847f800b4fd',
  'department': 'Directing',
  'gender': 2,
  'id': 1704,
  'job': 'Director',
  'name': 'Gore Verbinski'},
 {'credit_id': '52fe4232c3a36847f800b54f',
  'department': 'Production',
  'gender': 2,
  'id': 770,
  'job': 'Producer',
  'name': 'Jerry Bruckheimer'},
 {'credit_id': '52fe4232c3a36847f800b503',
  'department': 'Writing',
  'gender': 2,
  'id': 1705,
  'job': 'Screenplay',
  'name': 'Ted Elliott'},
 {'credit_id': '52fe4232c3a36847f800b509',
  'department': 'Writing',
  'gender': 2,
  'id': 1706,
  'job': 'Screenplay',
  'name': 'Terry Rossio'},
 {'credit_id': '52fe4232c3a36847f800b57f',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '52fe4232c3a36847f800b585',
  'department': 'Editing',
  'gender': 2,
  'id': 1722,
  'job': 'Editor',
  'name': 'Craig Wood'},
 {'credit_id': '52fe4232c3a36847f800b573',
  'department': 'Sound',
  'gender': 2,
  'id': 947,
  'job': 'Original Music Composer',
  'name': 'Hans Zimmer'},
 {'credit_id': '52fe4232c3a36847f800b555',
  'department': 'Production',
  'gender': 2,
  'id': 2444,
  'job': 'Executive Producer',
  'name': 'Mike Stenson'},
 {'credit_id': '52fe4232c3a36847f800b561',
  'department': 'Production',
  'gender': 2,
  'id': 2445,
  'job': 'Producer',
  'name': 'Eric McLeod'},
 {'credit_id': '52fe4232c3a36847f800b55b',
  'department': 'Production',
  'gender': 2,
  'id': 2446,
  'job': 'Producer',
  'name': 'Chad Oman'},
 {'credit_id': '52fe4232c3a36847f800b567',
  'department': 'Production',
  'gender': 0,
  'id': 2447,
  'job': 'Producer',
  'name': 'Peter Kohn'},
 {'credit_id': '52fe4232c3a36847f800b56d',
  'department': 'Production',
  'gender': 0,
  'id': 2448,
  'job': 'Producer',
  'name': 'Pat Sandston'},
 {'credit_id': '52fe4232c3a36847f800b58b',
  'department': 'Production',
  'gender': 1,
  'id': 2215,
  'job': 'Casting',
  'name': 'Denise Chamian'},
 {'credit_id': '52fe4232c3a36847f800b597',
  'department': 'Art',
  'gender': 2,
  'id': 1226,
  'job': 'Production Design',
  'name': 'Rick Heinrichs'},
 {'credit_id': '52fe4232c3a36847f800b59d',
  'department': 'Art',
  'gender': 2,
  'id': 553,
  'job': 'Art Direction',
  'name': 'John Dexter'},
 {'credit_id': '52fe4232c3a36847f800b591',
  'department': 'Production',
  'gender': 1,
  'id': 3311,
  'job': 'Casting',
  'name': 'Priscilla John'},
 {'credit_id': '52fe4232c3a36847f800b5a3',
  'department': 'Art',
  'gender': 1,
  'id': 4032,
  'job': 'Set Decoration',
  'name': 'Cheryl Carasik'},
 {'credit_id': '52fe4232c3a36847f800b5a9',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 4033,
  'job': 'Costume Design',
  'name': 'Liz Dann'},
 {'credit_id': '52fe4232c3a36847f800b5af',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 4034,
  'job': 'Costume Design',
  'name': 'Penny Rose'},
 {'credit_id': '56427ce8c3a3686a53000d8b',
  'department': 'Sound',
  'gender': 2,
  'id': 5132,
  'job': 'Music Supervisor',
  'name': 'Bob Badami'},
 {'credit_id': '55993c15c3a36855db002f33',
  'department': 'Art',
  'gender': 2,
  'id': 146439,
  'job': 'Conceptual Design',
  'name': 'James Ward Byrkit'},
 {'credit_id': '52fe4232c3a36847f800b5b9',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 406204,
  'job': 'Makeup Department Head',
  'name': 'Ve Neill'},
 {'credit_id': '56e47f7892514132690017bd',
  'department': 'Crew',
  'gender': 2,
  'id': 1259516,
  'job': 'Stunts',
  'name': 'John Dixon'},
 {'credit_id': '5740be639251416597000849',
  'department': 'Crew',
  'gender': 0,
  'id': 1336716,
  'job': 'CGI Supervisor',
  'name': 'Dottie Starling'},
 {'credit_id': '56427c639251412fc8000dc1',
  'department': 'Directing',
  'gender': 1,
  'id': 1344278,
  'job': 'Script Supervisor',
  'name': 'Pamela Alch'},
 {'credit_id': '57083101c3a3681d320004e6',
  'department': 'Crew',
  'gender': 0,
  'id': 1368867,
  'job': 'Special Effects Coordinator',
  'name': 'Allen Hall'},
 {'credit_id': '56427d5ec3a3686a62000d4a',
  'department': 'Sound',
  'gender': 0,
  'id': 1368884,
  'job': 'Music Editor',
  'name': 'Melissa Muik'},
 {'credit_id': '56427c7b9251412fd4000e07',
  'department': 'Directing',
  'gender': 1,
  'id': 1395290,
  'job': 'Script Supervisor',
  'name': 'Sharron Reynolds'},
 {'credit_id': '56427d2bc3a3686a53000d9b',
  'department': 'Sound',
  'gender': 0,
  'id': 1399327,
  'job': 'Music Editor',
  'name': 'Barbara McDermott'},
 {'credit_id': '56427cb4c3a3686a53000d87',
  'department': 'Directing',
  'gender': 1,
  'id': 1400738,
  'job': 'Script Supervisor',
  'name': 'Karen Golden'},
 {'credit_id': '56427d169251412fd4000e23',
  'department': 'Sound',
  'gender': 0,
  'id': 1534197,
  'job': 'Music Editor',
  'name': 'Katie Greathouse'}]

In [48]:
def director_(data):
    parsedata = json.loads(data)
    name=''
    for items in parsedata:
        if items['job']=='Director':
            name = items['name']
            break
    return name

In [47]:
 json.loads(df['crew'][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [49]:
df['director']=df['crew'].apply(director_)

In [122]:
df['director'].str.lower()

0           james cameron
1          gore verbinski
2              sam mendes
3       christopher nolan
4          andrew stanton
              ...
4798     robert rodriguez
4799         edward burns
4800          scott smith
4801          daniel hsia
4802     brian herzlinger
Name: director, Length: 4803, dtype: object

In [137]:
def join_name(data):
    result = ''.join(data.lower().split())
    return result

In [138]:
join_name('James Cameron')

'jamescameron'

In [139]:
df['director']=df['director'].apply(join_name)

In [140]:
df['director']

0           jamescameron
1          goreverbinski
2              sammendes
3       christophernolan
4          andrewstanton
              ...
4798     robertrodriguez
4799         edwardburns
4800          scottsmith
4801          danielhsia
4802     brianherzlinger
Name: director, Length: 4803, dtype: object

In [51]:
df.rename(columns={
    'name':'actors'
},inplace=True)

In [52]:
df.head()

,budget,genres,id,keywords,original_language,spoken_languages,crew,actors,director
0,237000000,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,en,English EspaÃ±ol,"[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",samworthington zoesaldana sigourneyweaver step...,James Cameron
1,300000000,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,en,English,"[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",johnnydepp orlandobloom keiraknightley stellan...,Gore Verbinski
2,245000000,Action Adventure Crime,206647,spy based on novel secret agent sequel mi6 bri...,en,FranÃ§ais English EspaÃ±ol Italiano Deutsch,"[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",danielcraig christophwaltz lÃ©aseydoux ralphfie...,Sam Mendes
3,250000000,Action Crime Drama Thriller,49026,dc comics crime fighter terrorist secret ident...,en,English,"[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",christianbale michaelcaine garyoldman annehath...,Christopher Nolan
4,260000000,Action Adventure Science Fiction,49529,based on novel mars medallion space travel pri...,en,English,"[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",taylorkitsch lynncollins samanthamorton willem...,Andrew Stanton

In [53]:
df.drop(columns=['budget','crew'],inplace=True)

In [54]:
df.head()

,genres,id,keywords,original_language,spoken_languages,actors,director
0,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,en,English EspaÃ±ol,samworthington zoesaldana sigourneyweaver step...,James Cameron
1,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,en,English,johnnydepp orlandobloom keiraknightley stellan...,Gore Verbinski
2,Action Adventure Crime,206647,spy based on novel secret agent sequel mi6 bri...,en,FranÃ§ais English EspaÃ±ol Italiano Deutsch,danielcraig christophwaltz lÃ©aseydoux ralphfie...,Sam Mendes
3,Action Crime Drama Thriller,49026,dc comics crime fighter terrorist secret ident...,en,English,christianbale michaelcaine garyoldman annehath...,Christopher Nolan
4,Action Adventure Science Fiction,49529,based on novel mars medallion space travel pri...,en,English,taylorkitsch lynncollins samanthamorton willem...,Andrew Stanton

In [55]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4803 non-null   int64
 1   title   4803 non-null   object
 2   cast    4803 non-null   object
 3   crew    4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [56]:
df['title']=df2['title']

In [141]:
df.head()

,genres,id,keywords,original_language,spoken_languages,actors,director,title,tags
0,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,en,English EspaÃ±ol,samworthington zoesaldana sigourneyweaver step...,jamescameron,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,en,English,johnnydepp orlandobloom keiraknightley stellan...,goreverbinski,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...
2,Action Adventure Crime,206647,spy based on novel secret agent sequel mi6 bri...,en,FranÃ§ais English EspaÃ±ol Italiano Deutsch,danielcraig christophwaltz lÃ©aseydoux ralphfie...,sammendes,Spectre,Action Adventure Crime spy based on novel secr...
3,Action Crime Drama Thriller,49026,dc comics crime fighter terrorist secret ident...,en,English,christianbale michaelcaine garyoldman annehath...,christophernolan,The Dark Knight Rises,Action Crime Drama Thriller dc comics crime fi...
4,Action Adventure Science Fiction,49529,based on novel mars medallion space travel pri...,en,English,taylorkitsch lynncollins samanthamorton willem...,andrewstanton,John Carter,Action Adventure Science Fiction based on nove...

In [101]:
df['keywords'].shape

(4803,)

In [104]:
import numpy as np

In [105]:
a = np.array([' ']*4803)

In [117]:
space_df=pd.DataFrame(a)

In [118]:
df['genres']+space_df[0]+df['keywords']

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united statesâ€“mexico bar...
4799                                      Comedy Romance
4800    Comedy Drama Romance TV Movie date love at fir...
4801
4802     Documentary obsession camcorder crush dream girl
Length: 4803, dtype: object

In [142]:
df['tags']=df['genres']+space_df[0]+df['keywords']+space_df[0]+df['actors']+space_df[0]+df['director']

In [143]:
df['tags'][0]

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez jamescameron'

In [144]:
df.head()

,genres,id,keywords,original_language,spoken_languages,actors,director,title,tags
0,Action Adventure Fantasy Science Fiction,19995,culture clash future space war space colony so...,en,English EspaÃ±ol,samworthington zoesaldana sigourneyweaver step...,jamescameron,Avatar,Action Adventure Fantasy Science Fiction cultu...
1,Adventure Fantasy Action,285,ocean drug abuse exotic island east india trad...,en,English,johnnydepp orlandobloom keiraknightley stellan...,goreverbinski,Pirates of the Caribbean: At World's End,Adventure Fantasy Action ocean drug abuse exot...
2,Action Adventure Crime,206647,spy based on novel secret agent sequel mi6 bri...,en,FranÃ§ais English EspaÃ±ol Italiano Deutsch,danielcraig christophwaltz lÃ©aseydoux ralphfie...,sammendes,Spectre,Action Adventure Crime spy based on novel secr...
3,Action Crime Drama Thriller,49026,dc comics crime fighter terrorist secret ident...,en,English,christianbale michaelcaine garyoldman annehath...,christophernolan,The Dark Knight Rises,Action Crime Drama Thriller dc comics crime fi...
4,Action Adventure Science Fiction,49529,based on novel mars medallion space travel pri...,en,English,taylorkitsch lynncollins samanthamorton willem...,andrewstanton,John Carter,Action Adventure Science Fiction based on nove...

In [68]:
df.describe()

                  id
count    4803.000000
mean    57165.484281
std     88694.614033
min         5.000000
25%      9014.500000
50%     14629.000000
75%     58610.500000
max    459488.000000

In [145]:
df['tags'][0]

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez jamescameron'

In [83]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Requirement already satisfied: click in c:\users\suraj\appdata\roaming\python\python38\site-packages (from nltk) (8.1.5)
Requirement already satisfied: joblib in c:\users\suraj\appdata\roaming\python\python38\site-packages (from nltk) (1.3.1)
Collecting regex>=2021.8.3 (from nltk)
  Obtaining dependency information for regex>=2021.8.3 from https://files.pythonhosted.org/packages/ec/1a/54672edc40464035adcb4df336399882c39bc8cec32f0cafc2a589bd423a/regex-2023.6.3-cp38-cp38-win_amd64.whl.metadata
  Downloading regex-2023.6.3-cp38-cp38-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/42.0 kB ? eta -:--:--
     ---------------------------------------- 42.0/42.0 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\users\suraj\appdata\roaming\python\python38\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\suraj\appdata\roaming\python\python38\site-packages (from click->nltk) (0.4.6)
Downloading regex-2023.6.3-cp38-cp38-win_amd64.whl (268 kB)
   ---------------------------------------- 0.0/268.1 kB ? eta -:--:--
   ---------------------------------------- 268.1/268.1 kB 8.1 MB/s eta 0:00:00
Installing collected packages: regex, nltk
Successfully installed nltk-3.8.1 regex-2023.6.3

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

[notice] A new release of pip is available: 23.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [95]:
import nltk

In [154]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [157]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [159]:
stem('Hello Brothe How Are you')

'hello broth how are you'

In [162]:
df['tags']=df['tags'].apply(stem)

In [163]:
df['tags']

0       action adventur fantasi scienc fiction cultur ...
1       adventur fantasi action ocean drug abus exot i...
2       action adventur crime spi base on novel secret...
3       action crime drama thriller dc comic crime fig...
4       action adventur scienc fiction base on novel m...
                              ...
4798    action crime thriller unit statesâ€“mexico barri...
4799    comedi romanc edwardburn kerrybishÃ© marshadiet...
4800    comedi drama romanc tv movi date love at first...
4801    danielhenney elizacoup billpaxton alanruck zhu...
4802    documentari obsess camcord crush dream girl dr...
Name: tags, Length: 4803, dtype: object

In [166]:
from sklearn.feature_extraction.text import CountVectorizer

In [167]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [168]:
vector=cv.fit_transform(df['tags']).toarray()

In [169]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [170]:
data9=pd.DataFrame(cv.get_feature_names_out())

In [171]:
data9.sample(5)

                0
288    ashleyjudd
243     apocalypt
4965         wyom
707        cartel
2419  josephfienn

In [172]:
from sklearn.metrics.pairwise import cosine_similarity

In [173]:
cosine_similarity(vector)

array([[1.        , 0.09365858, 0.05780733, ..., 0.07347184, 0.        ,
        0.        ],
       [0.09365858, 1.        , 0.07715167, ..., 0.04902903, 0.        ,
        0.        ],
       [0.05780733, 0.07715167, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.07347184, 0.04902903, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [175]:
similarity=cosine_similarity(vector)

In [245]:
similarity

array([[1.        , 0.09365858, 0.05780733, ..., 0.07347184, 0.        ,
        0.        ],
       [0.09365858, 1.        , 0.07715167, ..., 0.04902903, 0.        ,
        0.        ],
       [0.05780733, 0.07715167, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.07347184, 0.04902903, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [181]:
df['title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4798                                 El Mariachi
4799                                   Newlyweds
4800                   Signed, Sealed, Delivered
4801                            Shanghai Calling
4802                           My Date with Drew
Name: title, Length: 4803, dtype: object

In [188]:
df[df['title']=='Avatar'].index[0]

0

In [213]:
df.iloc[2403,7]

'Aliens'

In [192]:
distances=similarity[0]

In [225]:
sorted_array=sorted(enumerate(distances),key=lambda x:x[1],reverse=True)
for item in sorted_array[1:6]:
    df.iloc[item[0],7]

In [195]:
for index,dist in enumerate(distances):

In [217]:
movie ='Avatar'
movie.lower()

'avatar'

In [221]:
df['title'].str.lower()

0                                         avatar
1       pirates of the caribbean: at world's end
2                                        spectre
3                          the dark knight rises
4                                    john carter
                          ...
4798                                 el mariachi
4799                                   newlyweds
4800                   signed, sealed, delivered
4801                            shanghai calling
4802                           my date with drew
Name: title, Length: 4803, dtype: object

In [230]:
def recomend_movie(movie):
    movie = movie.lower()
    rec_movies=[]
    movie_index = df[df['title'].str.lower()==movie].index[0]
    distances = similarity[movie_index]
    sorted_array=sorted(enumerate(distances),key=lambda x:x[1],reverse=True)
    for item in sorted_array[1:6]:
        rec_movies.append(df.iloc[item[0],7])
    return rec_movies

In [236]:
recomend_movie('spectre')

['Quantum of Solace', 'Skyfall', 'Die Another Day', 'Goldfinger', 'Dr. No']

In [237]:
import pickle

In [238]:
pickle.dump(df,open('movies.pkl','wb'))

In [244]:
np.array(df['title'].values)

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [246]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [250]:
import requests
from PIL import Image
from io import BytesIO

In [251]:
def get_movie_poster(movie_title):
    api_key = 'd84abdce4b7b8a069bdb83d14a36aff7'
    base_url = 'https://api.themoviedb.org/3/search/movie'
    params = {'api_key': api_key, 'query': movie_title}

    response = requests.get(base_url, params=params)
    data = response.json()

    if data['results']:
        poster_path = data['results'][0]['poster_path']
        poster_url = f"https://image.tmdb.org/t/p/w500{poster_path}"
        return poster_url
    else:
        return None

In [252]:
get_movie_poster('Avatar')

'https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg'